export const TransferEmpIntenallySpecial = {
    kt_aside_menu: "#kt_aside_menu",
    EmployeeInformation: "#leftbar1_divPersonal",
    TransferModify: "#leftbar1_lblleft_Usermenu_Transfer",
    AddButton: "#ctl00_ContentTitleRight_RadToolBar1 a[title='เพิ่ม']",
    SaveButton: "#ctl00_ContentTitleRight_RadToolBar1 a[title='บันทึก']",
    CancelButton: "#ctl00_ContentTitleRight_RadToolBar1 a[title='ยกเลิก']",
    ConfirmSaveButton: '//*[@id="confirm1769052325479_content"]/div/div[2]/button[1]',
    TransferModifyDropdown: "#ctl00_dropdown_ddlMenu_Input",
    OptionSpecialTransfer: 'li:has-text("โอนประวัติพนักงานภายในแบบพิเศษ")',
    PersonCodeInput: "#MainContent_Txt_PersonCode",
    PersonCodeSearch: "#ctl00_MainContent_btnSearch",
    AdjustDatePicker: '//*[@id="MainContent_Div9"]/div/div/div[1]/div[2]/div/i',
    EffectiveDatePicker: '//*[@id="MainContent_Div9"]/div/div/div[1]/div[3]/div/i',
    NotesInput: "#MainContent_TxtDetails",
    SectionCmb1Dropdown: "#ctl00_MainContent_Combo_Cmb1Transfer_Input",
    DepartmentCmb2Dropdown: "#ctl00_MainContent_Combo_Cmb2Transfer_Input",
    DivisionCmb3Dropdown: "#ctl00_MainContent_Combo_Cmb3Transfer_Input",
    LevelCmb4Dropdown: "#ctl00_MainContent_Combo_Cmb4Transfer_Input",
    WorkLocationCmb5Dropdown: "#ctl00_MainContent_Combo_Cmb5Transfer_Input",
    ScopeOfWorkCmb6Dropdown: "#ctl00_MainContent_Combo_Cmb6Transfer_Input",
    CostCenterCmb7Dropdown: "#ctl00_MainContent_Combo_Cmb7Transfer_Input",
    GroupApproveCmb8Dropdown: "#ctl00_MainContent_Combo_Cmb8Transfer_Input",
    PositionDropdown: "#ctl00_MainContent_Combo_PositionTransfer_Input",
    LevelDropdown: "#ctl00_MainContent_Combo_LevelTransfer_Input",
    ContractTypeDropdown: "#ctl00_MainContent_Combo_ContractTransfer_Input",
    CurrentSalaryInput: "#MainContent_TxtSalaryCurrent",
    EmpTypeDropdown: "#ctl00_MainContent_Combo_EmpTypeTransfer_Input",
    TypeProcessDropdown: "#ctl00_MainContent_Combo_TypeProcessSalaryTransfer_Input",
    TransferSalaryInput: "#MainContent_TxtSalaryTransfer",
    ErrorPopup: '.RadWindow:has(.rwTitle:text("คำเตือน"))',
    SearchEmpPopup: '.RadWindow:has(.rwTitle:text("ค้นหาพนักงาน"))',
    OkBtn: '.rwOkBtn',
    SearchPersonCodeInput: '//*[@id="MainContent_txt_Search"]',
    SearchPersonCodeButton: '//*[@id="MainContent_btnSearch"]',
    SearchTypeDropdown:'//*[@id="ctl00_MainContent_Combo_Condition"]/span',
    SearchTypeDropdownList:"#ctl00_MainContent_Combo_Condition_DropDown .rcbItem",
    CurrentPersonNameInput: '#MainContent_txtNameEmp',
    Cmb3CurrentInput: '#ctl00_MainContent_Combo_Cmb3Current_Input',
    CurrentPosition: '#ctl00_MainContent_Combo_PositionCurrent_Input',
    CurrentLevel: '#ctl00_MainContent_Combo_LevelCurrent_Input',
    CurrentTypeSalary: '#ctl00_MainContent_Combo_TypeProSalaryCurrent_Input',

}