export const TransferEmpIntenallySpecial = {
    kt_aside_toggler: '//*[@id="kt_aside_brand"]',
    EmployeeInformation: '//*[@id="leftbar1_lblMenu_EmployeeInformation"]',
    TransferModify: '//*[@id="leftbar1_lblleft_Usermenu_Transfer"]',
    AddButton: '//*[@id="ctl00_ContentTitleRight_RadToolBar1"]/div/div/div/ul/li[1]/a',
    SaveButton: '//*[@id="ctl00_ContentTitleRight_RadToolBar1"]/div/div/div/ul/li[2]/a',
    CancelButton: '//*[@id="ctl00_ContentTitleRight_RadToolBar1"]/div/div/div/ul/li[3]/a',
    TransferModifyDropdown: '//*[@id="ctl00_dropdown_ddlMenu_Input"]',
    PersonCodeInput: '//*[@id="MainContent_Txt_PersonCode"]',
    PersonCodeSearch: '//*[@id="ctl00_MainContent_btnSearch"]',
    PersoneCodePopUpCloseButton: '//*[@id="RadWindowWrapper_ctl00_MainContent_Report1"]/div[1]/div/ul/li/span',
    PersoneCodePopUpConditionDropdown:'//*[@id="ctl00_MainContent_Combo_Condition_Input"]',
    PersonCodePopUpSearchInput: '//*[@id="MainContent_txt_Search"]',
    PersonCodePopUpSearchButton: '//*[@id="MainContent_btnSearch"]',
    PersoneCodePopUpPageSizeDropdown: '//*[@id="ctl00_MainContent_GridShowdata_ctl00_ctl03_ctl01_PageSizeComboBox"]/span/button',
    PersonCodePopUpNextPageButton: '//*[@id="ctl00_MainContent_GridShowdata_ctl00_Pager"]/tbody/tr/td/div/div[3]/button[1]',
    PersonCodePopUpLastPageButton: '//*[@id="ctl00_MainContent_GridShowdata_ctl00_Pager"]/tbody/tr/td/div/div[3]/button[2]',
    PersonCodePopUpPreviousPageButton: '//*[@id="ctl00_MainContent_GridShowdata_ctl00_Pager"]/tbody/tr/td/div/div[1]/button[2]',
    PersonCodePopUpFirstPageButton: '//*[@id="ctl00_MainContent_GridShowdata_ctl00_Pager"]/tbody/tr/td/div/div[1]/button[1]',
    AdjustDatePicker: '//*[@id="MainContent_TxtSaveDate"]',
    EffectiveDatePicker: "//input[@id='MainContent_TxtTranferDate']",
    NotesInput: "//textarea[@id='MainContent_TxtDetails']",
    SectionCmb1Dropdown: "//div[@id='ctl00_MainContent_Combo_Cmb1Transfer']/span[@class='rcbInner rcbExpanded rcbFocused']",
    DepartmentCmb2Dropdown: "//div[@id='ctl00_MainContent_Combo_Cmb2Transfer']/span[@class='rcbInner rcbFocused']",
    DivisionCmb3Dropdown: "//div[@id='ctl00_MainContent_Combo_Cmb3Transfer']/span[@class='rcbInner rcbFocused']",
    LevelCmb4Dropdown: "//div[@id='ctl00_MainContent_Combo_Cmb4Transfer']/span[@class='rcbInner rcbExpanded rcbFocused']",
    WorkLocationCmb5Dropdown: "//div[@id='ctl00_MainContent_Combo_Cmb5Transfer']/span[@class='rcbInner rcbExpanded rcbFocused']",
    ScopeOfWorkCmb6Dropdown: "//div[@id='ctl00_MainContent_Combo_Cmb6Transfer']/span[@class='rcbInner rcbExpanded rcbFocused']",
    CostCenterCmb7Dropdown: "//div[@id='ctl00_MainContent_Combo_Cmb7Transfer']/span[@class='rcbInner rcbExpanded rcbFocused']",
    GroupApproveCmb8Dropdown: "//div[@id='ctl00_MainContent_Combo_Cmb8Transfer']/span[@class='rcbInner rcbHovered']",
    PositionDropdown: "//div[@id='ctl00_MainContent_Combo_PositionTransfer']/span[@class='rcbInner rcbHovered']",
    LevelDropdown: "//div[@id='ctl00_MainContent_Combo_LevelTransfer']/span[@class='rcbInner rcbExpanded rcbFocused']",
    ContractTypeDropdown: "//div[@id='ctl00_MainContent_Combo_ContractTransfer']/span[@class='rcbInner rcbExpanded rcbFocused']",
    CurrentSalaryInput: "//input[@id='MainContent_TxtSalaryCurrent']",
    EmpTypeDropdown: "//div[@id='ctl00_MainContent_Combo_EmpTypeTransfer']/span[@class='rcbInner rcbHovered']",
    TypeProcessDropdown: "//div[@id='ctl00_MainContent_Combo_TypeProcessSalaryTransfer']/span[@class='rcbInner rcbExpanded rcbFocused']",
    TransferSalaryInput: "//input[@id='MainContent_TxtSalaryTransfer']",

}