


export const SelEmp = {

    // EmpDropdownMenu
    EmpDropdown: '#ctl00_dropdown_ddlMenu_Input',
    // General Information
    EmployeeInformation: '#leftbar1_divPersonal',
    PersonnelButton: '#leftbar1_lblleft_Usermenu_Personal',
    TransferButton: '#leftbar1_lblleft_Usermenu_Transfer',
    ConfirmTFButton: '#leftbar1_lblConfirmTransferAdjustment',
    ApproveEmployeeFromRecruitButton: '#leftbar1_lblApproveEmployeeFromRecruit',
    ResignationNoteButton: '#leftbar1_lblleft_Usermenu_WebResign',
    ReportButton: '#leftbar1_lblleft_Usermenu_Report',

    AddPersonnelButton: '#ctl00_ContentTitleRight_RadToolBar1 > div > div > div > ul > li:nth-child(1) > a',
    DropdownTitle: '#ctl00_MainContent_Combo_Initial_Input',
    DropdownList: '#ctl00_MainContent_Combo_Initial_DropDown > div.rcbScroll.rcbWidth > ul > li.rcbHovered.rcbTemplate > table > tbody > tr > td:nth-child(2)',
    DropdownList2: '#ctl00_MainContent_Combo_Initial_DropDown',
    NameTH: '#MainContent_Txt_FnameT',
    LastNameTH: '#MainContent_Txt_LnameT',
    NameEN: '#MainContent_Txt_FnameE',
    LastNameEN: '#MainContent_Txt_LnameE',
    EmployeeNumber: '#MainContent_Txt_PersonCode',
    PersonCardID: '#MainContent_Txt_PersonCardID',
    StartDate: '#MainContent_TxtStartDate',
    ServiceYear: '#MainContent_Txt_AgeWork',
    DropdownEmpType: '#ctl00_MainContent_Combo_EmpType_Input',
    DropdownEmpTypeItemM: '//td[normalize-space()="M"]',
    DropdownEmpTypeItemD: '//td[normalize-space()="D"]',
    DropdownLevel: '#ctl00_MainContent_Combo_Level_Input',
    DropdownLevelListA: '//td[normalize-space()="A"]',
    DropdownLevelListB: '//td[normalize-space()="B"]',
    PayrollType: '#ctl00_MainContent_Combo_TypeProcessSalary_Input',
    PayrollTypeM: '//td[normalize-space()="รายเดือน"]',
    PayrollTypeD: '//td[normalize-space()="รายวัน"]',
    PermanentDate: '#MainContent_TxtPassDate',

    DateOfBirth: '#MainContent_TxtBirthDate',
    Age: '#MainContent_Txt_Age',
    Gender: '#ctl00_MainContent_Combo_Sex_Input',
    Gendermale: '//td[normalize-space()="ชาย"]',
    Genderfemale: '//td[normalize-space()="หญิง"]',
    IdentificationNumber: '#MainContent_Txt_Identity',
    MaritalStatus: '#ctl00_MainContent_Combo_Marital_Input',
    MaritalStatusListM: '//td[normalize-space()="สมรส"]',
    MaritalStatusListS: '//td[normalize-space()="โสด"]',
    SaveButton: '//a[@title="บันทึก" and contains(@class, "fa-save")]',
    CancelButton: '//a[@title="ยกเลิก" and contains(@class, "fa-times")]',
    SelectEmp: '//span[@class="rtText"][contains(text(),"เพลไรท์ อิอิ")]',
    EditButton: '#ctl00_ContentTitleRight_RadToolBar1 > div > div > div > ul > li:nth-child(2) > a',
    LanguageButton: '#kt_header > div.kt-header__topbar > div.kt-header__topbar-item.kt-header__topbar-item--langs > div > button',
    LanguageButtonEN: '#topContent_lang1_lang_theme_en',
    position: '#ctl00_MainContent_Combo_Position_Input',
    positionList: '//td[normalize-space()="HRBP Manager"]',
    remark: '#MainContent_txtRemark',
    Section: '#ctl00_MainContent_Combo_Cmb1_Input',
    SectionList: '//td[normalize-space()="TH"]',
    Area: '#ctl00_MainContent_Combo_Cmb2_Input',
    AreaList: '//td[normalize-space()="Culinary"]',
    listArea: ' //div[@class="rtIn  rtDisabled rtDisabled"][normalize-space()="01 TH (2)"]',
    Department: '#ctl00_MainContent_Combo_Cmb3_Input',
    DepartmentList: '//td[normalize-space()="Marketing"]',
    part: '#ctl00_MainContent_Combo_Cmb4_Input',
    partList: '//td[normalize-space()="Business Development"]',
    worklocation: '#ctl00_MainContent_Combo_Cmb5_Input',
    worklocationList: '//td[normalize-space()="BTB"]',
    Benefitplan: '#ctl00_MainContent_Combo_Cmb6_Input',
    BenefitplanList: '//td[normalize-space()="การเงิน"]',
    ExpenseGroup: '#ctl00_MainContent_Combo_Cmb7_Input',
    ExpenseGroupList: '//td[normalize-space()="ภายใน"]',
    ApprovalGroup: '#ctl00_MainContent_Combo_Cmb8_Input',
    ApprovalGroupList: '//td[normalize-space()="A"]',
    DropdownJobgrade: '#ctl00_MainContent_Combo_JG_Input',
    DropdownJobgradeListA: '//td[normalize-space()="1.5"]',
    DropdownJobgradeListB: '//td[normalize-space()="2"]',
    EmploymentType: '#ctl00_MainContent_Combo_Contract_Input',
    EmploymentTypeList: '//td[normalize-space()="ปกติ"]',
    ProbationPeriod: '#MainContent_Txt_numProof',
    ContractStartDate: '#MainContent_TxtContractBegin',
    ContractEndDate: '#MainContent_TxtContractExpire',
    ProvidentFund: '#MainContent_Txt_PFID',
    ContractNumber: '#MainContent_Txt_ContactNo',
    DropdownSupervisor: '#ctl00_MainContent_Combo_CommanderID_Input',
    DropdownSupervisorList: '//td[normalize-space()="01"]',

    // Personnel Information
    PersonnelInformation: '#ctl00_MainContent_RadTabStrip1 > div > ul > li:nth-child(2) > span',
    Nickname: '#MainContent_TxtNickName',
    IDCardExpireDate: '#MainContent_TxtIdentityExpire',
    TaxID: '#MainContent_Txt_TaxID',
    SSONumber: '#MainContent_Txt_SSFID',
    SSOHospital: '#ctl00_MainContent_Combo_Hospital_Input',
    SSOHospitalList: '//li[normalize-space()="วิภาราม"]',
    Race: '#ctl00_MainContent_Combo_Citizen_Input',
    RaceList: '//em[normalize-space()="จีน"]',
    Religion: '#ctl00_MainContent_Combo_Religion_Input',
    ReligionList: '//td[normalize-space()="อิสลาม"]',
    Nationality: '#ctl00_MainContent_Combo_Nationality_Input',
    NationalityList: '//em[normalize-space()="พม่า"]',
    MilitaryStatus: '#ctl00_MainContent_Combo_StatusMilitary_Input',
    MilitaryStatusList: '//td[normalize-space()="ยกเว้น"]',
    PlaceOfBirth: '#MainContent_TxtPlace',
    Height: '#MainContent_TxtHight',
    Weight: '#MainContent_TxtWight',
    YestLicenseCar: '#MainContent_div_chkCarLicenceIDYes',
    LicenseNumber: '#MainContent_TxtCarLicenceID',
    DateDriverLicense: '#MainContent_TxtExpireCarStart',
    ExpireDateDriverLicense: '#MainContent_TxtExpireCarEnd',
    Checkhavecar: '//label[contains(text(),"มีรถยนต์")] ',
    YestLicenseMotorcycle: '#MainContent_div_ChkChkMotorLicence',
    MotorcycleLicenseNumber: '#MainContent_txtMotorLicence',
    DateMotorcycleLicense: '#MainContent_TxtExpireMotorStart',
    ExpireDateMotorcycleLicense: '#MainContent_TxtExpireMotorEnd',
    CheckhaveMotorcycle: '//label[contains(text(),"มีรถจักรยานยนต์")] ',
    Telinformation: '#MainContent_TxtTel ',
    Emailinformation: '#MainContent_TxtEmail',

    FirstNameEm: '#MainContent_txtFirstNameEmergency',
    LastNameEm: '#MainContent_txtLastNameEmergency',
    RelationshipEm: '#MainContent_txtRelationEmergency',
    PhoneNumberEm: '#MainContent_txtPhonenumberEmergency',
    CountryHouseAddress: '#ctl00_MainContent_Combo_CardNation_Input',
    CountryHouseAddressList: '//td[normalize-space()="ไทย"]',
    PostalCodeHouseAddress: '#MainContent_TxtCardPostID',
    ProvinceHouseAddress: '#ctl00_MainContent_Combo_CardProvince_Input',
    DistrictHouseAddress: '#ctl00_MainContent_Combo_CardAmphur_Input',
    DistrictHouseAddressList: '//td[normalize-space()="เมืองระนอง"]',
    SubDistrictHouseAddress: '#ctl00_MainContent_Combo_CardDistric_Input',
    SubDistrictHouseAddressList: '//td[normalize-space()="หงาว"]',
    HouseNoTH: '#MainContent_TxtCardAddress',
    HouseNoEng: '#MainContent_TxtCardAddressE',
    BuildingTH: '#MainContent_TxtCardBuilding',
    BuildingEng: '#MainContent_TxtCardBuildingE',
    AlleyTH: '#MainContent_TxtCardSoi ',
    AlleyEng: '#MainContent_TxtCardSoiE ',
    RoadTH: '#MainContent_TxtCardRoad',
    RoadEng: '#MainContent_TxtCardRoadE',

    // Current Address
    CurrentAddressCountry: '#ctl00_MainContent_Combo_CurrentNation_Input',
    CurrentAddressCountryList: '//td[normalize-space()="เยอรมัน"]',
    CurrentAddressPostalCode: '#MainContent_TxtCurrentPostID',
    CurrentAddressProvince: '#ctl00_MainContent_Combo_CurrentProvince_Input',
    CurrentAddressDistrict: '#ctl00_MainContent_Combo_CurrentAmphur_Input',
    CurrentAddressDistrictList: '//td[normalize-space()="คลองเตย"]',
    CurrentAddressSubDistrict: '#ctl00_MainContent_Combo_CurrentDistric_Input',
    CurrentAddressSubDistrictList: '//td[normalize-space()="คลองตัน"]',
    CurrentAddressHouseNoTH: '#MainContent_TxtCurrentAddress',
    CurrentAddressHouseNoEng: '#MainContent_TxtCurrentAddressE',
    CurrentAddressBuildingTH: '#MainContent_TxtCurrentBuilding',
    CurrentAddressBuildingEng: '#MainContent_TxtCurrentBuildingE',
    CurrentAddressAlleyTH: '#MainContent_TxtCurrentSoi',
    CurrentAddressAlleyEng: '#MainContent_TxtCurrentSoiE',
    CurrentAddressRoadTH: '#MainContent_TxtCurrentRoad',
    CurrentAddressRoadEng: '#MainContent_TxtCurrentRoadE',
    HBloodType: '#ctl00_MainContent_Combo_Blood_Input',
    HBloodTypeList: '//td[normalize-space()="A"]',
    HMedicalConditions: '#MainContent_txtCongenitalDisease',
    HInsuranceNumber: '#MainContent_TxtInsuranceNo',
    HExpireDate: '#MainContent_TxtExpireInsurance',

    // Language Information
    AddLanguageButton: '#ctl00_MainContent_GridSkillLanguage_ctl00_ctl02_ctl00_AddNewRecordButton',
    Language: 'td:has(div#ctl00_MainContent_GridSkillLanguage_ctl00_MainContent_GridSkillLanguage_ctl00_LanguageID)',
    LanguageComboBox: '#ctl00_MainContent_GridSkillLanguage_ctl00_MainContent_GridSkillLanguage_ctl00_LanguageID',
    LanguageList: '#ctl00_MainContent_GridSkillLanguage_ctl00_MainContent_GridSkillLanguage_ctl00_LanguageID_Combo_Lang_DropDown',
    ProficiencyTest: '#ctl00_MainContent_GridSkillLanguage_ctl00_MainContent_GridSkillLanguage_ctl00_LanguageTest_txtToeic',
    Score: '#ctl00_MainContent_GridSkillLanguage_ctl00_MainContent_GridSkillLanguage_ctl00_ScorePoint_txtScore',
    Listening: '#ctl00_MainContent_GridSkillLanguage_ctl00_MainContent_GridSkillLanguage_ctl00_ListeningPoint_txtListening',
    Reading: '#ctl00_MainContent_GridSkillLanguage_ctl00_MainContent_GridSkillLanguage_ctl00_ReadingPoint_txtReading',
    Writing: '#ctl00_MainContent_GridSkillLanguage_ctl00_MainContent_GridSkillLanguage_ctl00_WritingPoint_txtWriting',
    Speaking: '#ctl00_MainContent_GridSkillLanguage_ctl00_MainContent_GridSkillLanguage_ctl00_SpeakingPoint_txtSpeaking',

    // Spouse Information
    TabFamily: '//*[@id="ctl00_MainContent_RadTabStrip1"]/div/ul/li[3]/span/span',
    TitleSpouse: '#ctl00_MainContent_Combo_IntitalMate_Input',
    TitleSpouseList: '//td[normalize-space()="นางสาว"]',
    FirstNameSpouse: '#MainContent_TxtMateFname',
    LastNameSpouse: '#MainContent_TxtMateLname',
    IdentificationNumberSpouse: '#MainContent_TxtMateIdentity',
    BirthDateSpouse: '#MainContent_TxtMateBirth',
    AgeSpouse: '#MainContent_TxtAgeMate',
    OccupationSpouse: '#ctl00_MainContent_Combo_MateOcc_Input',
    OccupationSpouseList: '//td[normalize-space()="ค้าขาย"]',
    PhoneNumberSpouse: '#MainContent_TxtMateTel',
    CountrySpouse: '#ctl00_MainContent_rcbpouseWorkCountry_Input',
    CountrySpouseList: '//td[normalize-space()="ไทย"]',
    PostcodeSpouse: '#MainContent_txtSpousePostcode',
    ProvinceSpouse: '#MainContent_txtSpouseWorkProvince',
    DistrictSpouse: '#ctl00_MainContent_rcbSpouseAuphur_Input',
    DistrictSpouseList: '//td[normalize-space()="เมืองระนอง"]',
    SubDistrictSpouse: '#ctl00_MainContent_rcbSpouseWorkSubdistrict_Input',
    SubDistrictSpouseList: '//td[normalize-space()="บางนอน"]',
    HouseNoSpouse: '#MainContent_txtSpouseWorkNo',
    AlleySpouse: '#MainContent_txtSpouseWorkAlley',
    RoadSpouse: '#MainContent_txtSpouseWorkRoad',
    RemarksSpouse: '#MainContent_txtSpouseWorkRemark',
    YearOfMarriageRegistration: '#MainContent_TxtYearMarital',
    ProvinceofRegistration: '#ctl00_MainContent_Combo_ProvMarital_Input',
    ProvinceofRegistrationList: '//td[normalize-space()="ปทุมธานี"]',
    DistrictofRegistration: '#ctl00_MainContent_Combo_AmphurMarital_Input',
    DistrictofRegistrationList: '//td[normalize-space()="ธัญบุรี"]',
    ProvinceofCertificateDisplay: '#ctl00_MainContent_Combo_MateProv_Input',
    ProvinceofCertificateDisplayList: '//td[normalize-space()="สมุทรปราการ"]',
    DistrictofCertificateDisplay: '#ctl00_MainContent_Combo_MateAmphur_Input',
    DistrictofCertificateDisplayList: '//td[normalize-space()="บางบ่อ"]',
    NumberofChildren: '#MainContent_TxtNumChild',
    NumberofSon: '#MainContent_TxtNumSon',
    NumberofDaughter: '#MainContent_TxtNumDaughter',

    // Child Information
    Tabchild: '//*[@id="ctl00_MainContent_RadTabStripFamily"]/div/ul/li[2]/span/span',
    Addchild: '#ctl00_MainContent_GridChildMate_ctl00_ctl02_ctl00_AddNewRecordButton',
    PageSizeComboBoxC: '#ctl00_MainContent_GridChildMate_ctl00_ctl03_ctl01_PageSizeComboBox_Input',
    PageSizeComboBoxListC: '#ctl00_MainContent_GridChildMate_ctl00_ctl03_ctl01_PageSizeComboBox_DropDown',
    Tablechild: '#ctl00_MainContent_GridChildMate .rgRow, #ctl00_MainContent_GridChildMate .rgAltRow',
    Levelchild: '#ctl00_MainContent_GridChildMate_ctl00_MainContent_GridChildMate_ctl00_ChildLevel_TxtChildLevel',
    Titlechild: '#ctl00_MainContent_GridChildMate_ctl00_MainContent_GridChildMate_ctl00_InitialID_Combo_ChildInitial_Input',
    Titlechildlist: '#ctl00_MainContent_GridChildMate_ctl00_MainContent_GridChildMate_ctl00_InitialID_Combo_ChildInitial_DropDown',
    FirstNamechild: '#ctl00_MainContent_GridChildMate_ctl00_MainContent_GridChildMate_ctl00_ChildNameNew_TxtChildNameNew',
    LastNamechild: '#ctl00_MainContent_GridChildMate_ctl00_MainContent_GridChildMate_ctl00_ChildSurnameNew_TxtChildSurnameNew',
    Genderchild: '#ctl00_MainContent_GridChildMate_ctl00_MainContent_GridChildMate_ctl00_SexID_Combo_ChildSex_Input',
    GenderchildlistM: '#ctl00_MainContent_GridChildMate_ctl00_MainContent_GridChildMate_ctl00_SexID_Combo_ChildSex_DropDown',
    Birthchild: '#ctl00_MainContent_GridChildMate_ctl00_MainContent_GridChildMate_ctl00_ChildBirth_TxtChildBirth_Grid',
    IdentificationNumberchild: '#ctl00_MainContent_GridChildMate_ctl00_MainContent_GridChildMate_ctl00_Child_IdentityID_TxtChild_IdentityID',
    Remarkschild: '#ctl00_MainContent_GridChildMate_ctl00_MainContent_GridChildMate_ctl00_ChildComment_TxtChildComment',

    // Parent FatharInformation
    TabParent: '//*[@id="ctl00_MainContent_RadTabStripFamily"]/div/ul/li[3]/span/span',
    RelationshipParent: '#ctl00_MainContent_Combo_family_Input',
    RelationshipParentList: '//li[normalize-space()="บิดา"]',
    TitleParent: '#ctl00_MainContent_Combo_IntitalFather_Input',
    TitleParentM: '#ctl00_MainContent_Combo_IntitalMother_Input',
    TitleParentList: '//td[normalize-space()="นาย"]',
    FirstNameParent: '#MainContent_TxtFatherName',
    LastNameParent: '#MainContent_TxtFatherSurName',
    IdentificationNumberParent: '#MainContent_TxtFatherIden',
    BirthDateParent: '#MainContent_TxtFatherBirth',
    AgeParent: '#MainContent_TxtFatherAge',
    OccupationParent: '#ctl00_MainContent_Combo_FatherOccupation_Input',
    OccupationParentList: '//td[normalize-space()="เกษียณอายุ"]',
    JobTitleParent: '#MainContent_txtPositionFather',
    PhoneNumberParent: '#MainContent_TxtFatherTel',
    CountryParent: '#ctl00_MainContent_rcbParentsCountryshow1_Input',
    CountryParentList: '//td[normalize-space()="ไทย"]',
    PostcodeParent: '#MainContent_txtParentspostcodeshow1',
    ProvinceParent: '#MainContent_txtParentsprovinceshow1',
    DistrictParent: '#ctl00_MainContent_rcbParentsDistrictshow1_Input',
    DistrictParentList: '//td[normalize-space()="ขาณุวรลักษบุรี"]',
    SubDistrictParent: '#ctl00_MainContent_rcbParentsSubdistrictshow1_Input',
    SubDistrictParentList: '//td[normalize-space()="ยางสูง"]',
    HouseNoParent: '#MainContent_txtParentshouseshow1',
    BuildingParent: '#MainContent_txtBuildingparentsshow1',
    AlleyParent: '#MainContent_txtParentsAlleyshow1',
    RoadParent: '#MainContent_txtParentsRoadshow1',
    CountryParentWork: '#ctl00_MainContent_rcbParentsCountryaddshow1_Input',
    CountryParentListWork: '//td[normalize-space()="ไทย"]',
    PostcodeParentWork: '#MainContent_txtParentsPostaddcodeshow1',
    ProvinceParentWork: '#MainContent_txtParentsaddProvinceshow1',
    DistrictParentWork: '#ctl00_MainContent_rcbParentsDistrictaddshow1_Input',
    DistrictParentListWork: '//td[normalize-space()="จอมทอง"]',
    SubDistrictParentWork: '#ctl00_MainContent_rcbParentsSubdistrictaddshow1_Input',
    SubDistrictParentListWork: '//td[normalize-space()="บ้านหลวง"]',
    HouseNoParentWork: '#MainContent_txtParentsnoshow1',
    AlleyParentWork: '#MainContent_txtParentsaddalleyshow1',
    RoadParentWork: '#MainContent_txtParentsRoadaddshow1',
    RemarkParentWork: '#MainContent_txtParentsRemarksshow1',

    // Parent MotherInformation
    RelationshipParentListM: '//li[normalize-space()="มารดา"]',
    TitleParentListM: '//td[normalize-space()="นาง"]',
    FirstNameParentM: '#MainContent_TxtMotherName',
    LastNameParentM: '#MainContent_TxtMotherSurName',
    IdentificationNumberParentM: '#MainContent_TxtMotherIden',
    BirthDateParentM: '#MainContent_TxtMotherBirth',
    AgeParentM: '#MainContent_TxtMotherAge',
    OccupationParentM: '#ctl00_MainContent_Combo_MotherOccupation_Input',
    OccupationParentListM: '//td[normalize-space()="ค้าขาย"]',
    JobTitleParentM: '#MainContent_txtPositionMother',
    PhoneNumberParentM: '#MainContent_TxtMotherTel',
    CountryParentM: '#ctl00_MainContent_rcbParentsCountryshow2_Input',
    CountryParentListM: '//td[normalize-space()="พม่า"]',
    PostcodeParentM: '#MainContent_txtParentspostcodeshow2',
    ProvinceParentM: '#MainContent_txtParentsprovinceshow2',
    DistrictParentM: '#ctl00_MainContent_rcbParentsDistrictshow2_Input',
    DistrictParentListM: '//td[normalize-space()="เมืองระนอง"]',
    SubDistrictParentM: '#ctl00_MainContent_rcbParentsSubdistrictshow2_Input',
    SubDistrictParentListM: '//td[normalize-space()="บางนอน"]',
    HouseNoParentM: '#MainContent_txtParentshouseshow2',
    BuildingParentM: '#MainContent_txtBuildingparentsshow2',
    AlleyParentM: '#MainContent_txtParentsAlleyshow2',
    RoadParentM: '#MainContent_txtParentsRoadshow2',

    CountryParentWorkM: '#ctl00_MainContent_rcbParentsCountryaddshow2_Input',
    CountryParentListWorkM: '//td[normalize-space()="ไทย"]',
    PostcodeParentWorkM: '#MainContent_txtParentsPostaddcodeshow2',
    ProvinceParentWorkM: '#MainContent_txtParentsaddProvinceshow2',
    DistrictParentWorkM: '#ctl00_MainContent_rcbParentsDistrictaddshow2_Input',
    DistrictParentListWorkM: '//td[normalize-space()="เมืองระนอง"]',
    SubDistrictParentWorkM: '#ctl00_MainContent_rcbParentsSubdistrictaddshow2_Input',
    SubDistrictParentListWorkM: '//td[normalize-space()="บางนอน"]',
    HouseNoParentWorkM: '#MainContent_txtParentsnoshow2',
    AlleyParentWorkM: '#MainContent_txtParentsaddalleyshow2',
    RoadParentWorkM: '#MainContent_txtParentsRoadaddshow2',
    RemarkParentWorkM: '#MainContent_txtParentsRemarksshow2',

    // Sibling Information
    TabSibling: '//*[@id="ctl00_MainContent_RadTabStripFamily"]/div/ul/li[4]/span/span',
    AddSibling: '#ctl00_MainContent_GridFamily_ctl00_ctl02_ctl00_AddNewRecordButton',
    LevelSibling: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_RelativeLevel_TxtRelativeLevel',
    TitleSibling: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_InitialID_Combo_RelativelInitial_Input',
    TitleSiblingList: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_InitialID_Combo_RelativelInitial_DropDown',
    FirstNameSibling: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_RelativeNameNew_TxtRelativeNameNew',
    LastNameSibling: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_RelativeSurnameNew_TxtRelativeSurnameNew',
    BirthSibling: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_RelativeBirth_TxtRelativeBirth_Grid',
    OccupationSibling: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_OccupationID_combo_FamilyOccupation_Input',
    OccupationSiblingList: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_OccupationID_combo_FamilyOccupation_DropDown',
    JobTitleSibling: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_RelativePosition_TxtEmergencyLevel',
    PhoneNumberSibling: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_Relativetel_TxtRelativetel',
    RelationshipSibling: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_RelativeHave_TxtRelativeHave',
    AddressSibling: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_RelativeAddress_TxtRelativeAddress',
    RemarksSibling: '#ctl00_MainContent_GridFamily_ctl00_MainContent_GridFamily_ctl00_RelativeComment_TxtRelativeComment',

    // Education Information
    TabEducation: '//*[@id="ctl00_MainContent_RadTabStrip1"]/div/ul/li[4]/span/span',
    AddEducation: '#ctl00_MainContent_GridEducation_ctl00_ctl02_ctl00_AddNewRecordButton',
    EducationNo: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_EducateLevel_TxtEducateLevel',
    DegreeEducation: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_DegreeID_Combo_Degree_Input',
    DegreeEducationList: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_DegreeID_Combo_Degree_DropDown',
    FieldOfStudy: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_MajorID_Combo_Major_Input',
    FieldOfStudyList: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_MajorID_Combo_Major_DropDown',
    InstitutionEducation: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_InstituteID_Combo_Institute_Input',
    InstitutionEducationList: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_InstituteID_Combo_Institute_DropDown',
    CountryEducation: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_NationalityID_Combo_Nationality_Input',
    CountryEducationList: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_NationalityID_Combo_Nationality_DropDown',
    StartYear: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_YearIN_TxtYearIN',
    EndYear: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_YearOut_TxtYearOut',
    GPA: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_EducateGrade_TxtEducateGrade',
    RemarksEducation: '#ctl00_MainContent_GridEducation_ctl00_MainContent_GridEducation_ctl00_EducateComment_TxtEducateComment',

    // Experience Information
    TabExperience: '//*[@id="ctl00_MainContent_RadTabStrip1"]/div/ul/li[5]/span/span',
    AddExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_ctl02_ctl00_AddNewRecordButton',
    ExperienceNo: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkHisLevel_TxtWorkHisLevel',
    PositionExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_PosWorkHisName_TxtPosWorkHisName',
    ScopeOfWork: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkDetail_TxtWorkDetail',
    StartDateExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_DateInHis_TxtDateInHis_Grid',
    EndDateExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_DateOutHis_TxtDateOutHis_Grid',
    CompanyNameExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_OldCompany_TxtOldCompany',
    CountryExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkNation_Combo_WorkExpCardNation_Input',
    CountryExperienceList: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkNation_Combo_WorkExpCardNation_DropDown',
    PostcodeExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkPostID_txtOldWorkExpPostcode',
    ProvinceExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_NameProvince_TxtOldWorkExpProvince',
    DistrictExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkAmphur_Combo_WorkExpDistrict_Input',
    DistrictExperienceList: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkAmphur_Combo_WorkExpDistrict_DropDown',
    SubDistrictExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkDistric_Combo_WorkExpSubDistrict_Input',
    SubDistrictExperienceList: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkDistric_Combo_WorkExpSubDistrict_DropDown',
    NoExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkAddress_txtOldWorkExpHouseNo',
    AlleyExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkSoi_txtOldWorkExpAlley',
    RoadExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_WorkRoad_txtOldWorkExpRoad',
    PhoneNumberExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_OldCompanyTel_TxtOldCompanyTel',
    StartSalary: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_StartSalary_TxtStartSalary',
    EndSalary: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_LastSalary_TxtLastSalary',
    ReasonForLeaving: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_OutDetail_TxtOutDetail',
    DurationExperience: '#ctl00_MainContent_GridWorkHistory_ctl00_MainContent_GridWorkHistory_ctl00_ServiceTerm_TxtServiceTerm',

    // Guarantor Information
    TabGuarantor: '//*[@id="ctl00_MainContent_RadTabStrip1"]/div/ul/li[6]/span/span',
    AddGuarantor: '#ctl00_MainContent_GridGuarantor_ctl00_ctl02_ctl00_AddNewRecordButton',
    GuarantorNo: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorLevel_TxtGuarantorLevel',
    GuarantorName: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorName_TxtGuarantorName',
    GuarantorAge: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorAge_TxtGuarantorAge',
    GuarantorIdentityID: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorIdentID_TxtGuarantorIdentID',
    GuarantorIdentityExpire: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorIdentExp_TxtGuarantorIdentExp_Grid',
    GuarantorAddress: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorAdd_TxtGuarantorAdd',
    TelGuarantor: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorTel_TxtGuarantorTel',
    OccupationGuarantor: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_OccupationID_ComboGuarantor_Occupation_Input',
    OccupationGuarantorList: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_OccupationID_ComboGuarantor_Occupation_DropDown',
    PositionGuarantor: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorPosition_TxtGuarantor_Position',
    CompanyGuarantor: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorCompany_TxtGuarantorCompany',
    CompanyTelGuarantor: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorComTel_TxtGuarantorComTel',
    RelativeGuarantor: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorRelative_TxtGuarantorRelative',
    ContractGuarantor: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorContract_TxtGuarantorContract_Grid',
    GuarantorSalaryGuarantor: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorSalary_TxtGuarantorSalary',
    GuarantorBirthGuarantor: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuarantorBirth_TxtGuarantorBirth_Grid',
    GuaranteValueGuarantor: '#ctl00_MainContent_GridGuarantor_ctl00_MainContent_GridGuarantor_ctl00_GuaranteValue_TxtGuaranteValue',

    // Time Basic data Checkbox
    TabTime: '//*[@id="ctl00_MainContent_RadTabStrip1"]/div/ul/li[7]/span/span',
    TimeCheckIN: '#MainContent_PanelBasicInformation > div > div.col-md-12.mt-2 > div > div > div:nth-child(1) > label',
    TimeCheckOut: '#MainContent_PanelBasicInformation > div > div.col-md-12.mt-2 > div > div > div:nth-child(2) > label',
    PayLate: '#MainContent_PanelBasicInformation > div > div.col-md-12.mt-2 > div > div > div:nth-child(3) > label',
    CheckLate: '#MainContent_PanelBasicInformation > div > div.col-md-12.mt-2 > div > div > div.col-lg-3 > label',
    PayFood: '#MainContent_PanelBasicInformation > div > div:nth-child(2) > div > div > div:nth-child(1) > label',
    PayShift: '#MainContent_PanelBasicInformation > div > div:nth-child(2) > div > div > div:nth-child(2) > label',
    PayBeforce: '#MainContent_PanelBasicInformation > div > div:nth-child(2) > div > div > div:nth-child(3) > label',
    CheckBeforce: '#MainContent_PanelBasicInformation > div > div:nth-child(2) > div > div > div.col-lg-3 > label',
    NocutEarlyTime: '#MainContent_PanelBasicInformation > div > div:nth-child(3) > div > div > div:nth-child(1) > label',
    NocutLateTime: '#MainContent_PanelBasicInformation > div > div:nth-child(3) > div > div > div:nth-child(2) > label',
    WorkdayOT: '#MainContent_PanelBasicInformation > div > div:nth-child(3) > div > div > div.col-lg-3 > label',
    Timeinthedesignatedarea: '#MainContent_ckShift_Vichaiyut',
    DecLateB: '#MainContent_txtDecLateB',
    BeforceB: '#MainContent_txtDecBeforceB',
    PlateHoliday: '#ctl00_MainContent_Combo_PlateHoliday_Input',
    PlateHolidayList: '#ctl00_MainContent_Combo_PlateHoliday_DropDown',
    Shifttemplate: '#ctl00_MainContent_Combo_Shifttemplat_Input',
    ShifttemplateList: '#ctl00_MainContent_Combo_Shifttemplat_DropDown',

    // Time Basic data LeaveLevel
    LeaveLevel: '#ctl00_MainContent_Combo_Leave_Input',
    LeaveLevelList: '#ctl00_MainContent_Combo_Leave_DropDown',
    LeaveLastYearDay: '#MainContent_txtOldD',
    LeaveLastYearHour: '#MainContent_txtOldH',
    LeaveLastYearMinute: '#MainContent_txtOldM',
    LeaveUseLastYearDay: '#MainContent_txtUseD',
    LeaveUseLastYearHour: '#MainContent_txtUseH',
    LeaveUseLastYearMinute: '#MainContent_txtUseM',
    LeaveMoveLastYearDay: '#MainContent_txtMoveD',
    LeaveMoveLastYearHour: '#MainContent_txtMoveH',
    LeaveMoveLastYearMinute: '#MainContent_txtMoveM',
    LeaveThisYearDay: '#MainContent_txtNewD',
    LeaveThisYearHour: '#MainContent_txtNewH',
    LeaveThisYearMinute: '#MainContent_txtNewM',
    BusinessLeaveDay: '#MainContent_txtProrateLeaveNewD',
    BusinessLeaveHour: '#MainContent_txtProrateLeaveNewH',
    BusinessLeaveMinute: '#MainContent_txtProrateLeaveNewM',
    OTaccumulate: '#MainContent_txtOTSum_Year',
    Cumulativeleave: '#MainContent_txtYear_Leave4',

    // Time Basic data LeaveType
    TabOTsetting: '//*[@id="ctl00_MainContent_RadTabStrip2"]/div/ul/li[2]/span/span',
    CutOT: '#MainContent_PanelSetupOT > div > div > div:nth-child(1) > div > div > label',
    PayOT: '#MainContent_PanelSetupOT > div > div > div:nth-child(2) > div > div > label',
    OTPayB: '#MainContent_PanelSetupOT > div > div > div:nth-child(3) > div > div.col-lg-3 > label',
    TotalOT6All: '#MainContent_PanelSetupOT > div > div > div:nth-child(4) > div > div.col-lg-5 > label',
    OTAutoHDbyEmp: '#MainContent_divOTAutoHDByEMP > label',
    OTPayBBaht: '#MainContent_txtOTPayBH',
    OTBreak: '#MainContent_txtOTBreak',

    // Time Basic data Charge for Special
    TabCharge: '//*[@id="ctl00_MainContent_RadTabStrip2"]/div/ul/li[3]/span/span',
    Special1: '#MainContent_txtSpecial1',
    Special2: '#MainContent_txtSpecial2',
    Special3: '#MainContent_txtSpecial3',

    // Time Special allowances by working day Setting Shift
    TabSpecialallowances: '//*[@id="ctl00_MainContent_RadTabStrip2"]/div/ul/li[4]/span/span',
    RowCode1: '#ctl00_MainContent_GridFringeBenefit_ctl00_MainContent_GridFringeBenefit_ctl00_SP_Code_TxtSP_Code',
    RowBaht1: '#ctl00_MainContent_GridFringeBenefit_ctl00_MainContent_GridFringeBenefit_ctl00_SP_Money_TxtSP_Money',


    // Time Setting Shift
    TabSettingShift: '//*[@id="ctl00_MainContent_RadTabStrip2"]/div/ul/li[5]/span/span',
    ShiftGroup: '#ctl00_MainContent_rcbShiftGroup_Input',
    ShiftGroupList: '#ctl00_MainContent_rcbShiftGroup_DropDown',
    CheckBoxSunday: 'div:nth-child(2) > div:nth-child(2) > .col-lg-12 > .kt-checkbox > span',
    CheckBoxMonday: 'div:nth-child(3) > div:nth-child(2) > .col-lg-12 > .kt-checkbox > span',
    CheckBoxTuesday: 'div:nth-child(4) > div:nth-child(2) > .col-lg-12 > .kt-checkbox > span',
    CheckBoxWednesday: 'div:nth-child(5) > div:nth-child(2) > .col-lg-12 > .kt-checkbox > span',
    CheckBoxThursday: 'div:nth-child(6) > div:nth-child(2) > .col-lg-12 > .kt-checkbox > span',
    CheckBoxFriday: 'div:nth-child(7) > div:nth-child(2) > .col-lg-12 > .kt-checkbox > span',
    CheckBoxSaturday: 'div:nth-child(8) > div:nth-child(2) > .col-lg-12 > .kt-checkbox > span',

    SundayShift: '#MainContent_txtSunday',
    MondayShift: '#MainContent_txtMonday',
    TuesdayShift: '#MainContent_txtTuesday',
    WednesdayShift: '#MainContent_txtWednesday',
    ThursdayShift: '#MainContent_txtThursday',
    FridayShift: '#MainContent_txtFriday',
    SaturdayShift: '#MainContent_txtSaturday',

    rdoShiftWeek: '#rdoShiftWeek1 > label',
    rdoShiftAuto: '#rdoShiftAuto1 > label',

    // Payroll  Tax / SSO / Provident Fund
    TabPayroll: '//span[normalize-space()="ระบบเงินเดือน"]',
    TabTaxSSOProvidentFund: '//*[@id="ctl00_MainContent_RadTabStrip4"]/div/ul/li[1]/span/span',
    CalculateTax: '#MainContent_ckCheckBoxTax > label',
    IssuingPND3: '#MainContent_ckCheckBoxEmp3 > label',
    PND95: '#MainContent_ckCheckBoxROH > label',
    BranchTax: '#ctl00_MainContent_Combo_BranchTax_Input',
    CalTax: '#ctl00_MainContent_Combo_TaxType_Input',
    CalTaxList: '#ctl00_MainContent_Combo_TaxType_DropDown',
    FixedRateWithholdingTax: '#MainContent_txtTaxFix',
    PercentageBasedTax: '#MainContent_txtTaxPer',
    EmployeePaidTax: '#MainContent_pnrdoTaxModeP > label',
    CompanyPaidTax: '#MainContent_pnrdoTaxModeC > label',
    CompanyPaidSetting: '#MainContent_BtnConfigIncome',
    CompanyPaidSettingList: '#ctl00_MainContent_GridConfigIncome',
    BtnMoveRight: '#MainContent_BtnMoveRight',
    BtnSave: '#MainContent_BtnSave',

    // Social Security
    CalculateSSO: '#MainContent_ckCheckBoxSSF > label',
    CalculateKORTOR20: '#MainContent_ckCheckBox20 > label',
    Branchno: '#ctl00_MainContent_Combo_SSFID_Input',
    BranchnoList: '#ctl00_MainContent_Combo_SSFID_DropDown',
    BranchName: '#MainContent_txtBranchSSF',

    //ProvidentFund
    CalProvidentFund: '#MainContent_ckCheckBoxPF > label',
    Typeoffund: '#ctl00_MainContent_Combo_BranchPF_Input',
    TypeoffundList: '#ctl00_MainContent_Combo_BranchPF_DropDown',
    DateofFundEnrollment: '#MainContent_PFDateStart',
    DateofFundWithdrawal: '#MainContent_PFDateExit',
    FundInceptionDate: '#MainContent_starTagePF',
    BeneficiaryName: '#MainContent_Txt_nameBeneficiary',
    SerDurationCalEmp: '#MainContent_pnrdoEmpCalY > label',
    IndividualSetupEmp: '#MainContent_pnrdoEmpCalE > label',
    IndividualSetupValue: '#MainContent_txtPFPay',
    SerDurationCalCom: '#MainContent_pnrdoPFComCalY > label',
    IndividualSetupCom: '#MainContent_pnrdoPFComCalE > label',
    IndividualSetupComValue: '#MainContent_txtPFCPay',

    // ProvidentFund morethan 1
    CalProvidentFundmorethan: '#MainContent_ckCheckBoxPFOvr > label',
    Mastermorethan: '#ctl00_MainContent_btnBranchPFOvr',
    iframeMastermorethan: '#ctl00_RadWindow1_C > iframe',
    AddProvidentFundmorethan: '#ctl00_MainContent_GridBranchPFOvr_ctl00_ctl02_ctl00_AddNewRecordButton',
    NameProviden: '#ctl00_MainContent_GridBranchPFOvr_ctl00_MainContent_GridBranchPFOvr_ctl00_BranchPFID_Combo_BranchPFOvr_Input',
    NameProvidenList: '#ctl00_MainContent_GridBranchPFOvr_ctl00_MainContent_GridBranchPFOvr_ctl00_BranchPFID_Combo_BranchPFOvr_DropDown',
    RateEmp: '#ctl00_MainContent_GridBranchPFOvr_ctl00_MainContent_GridBranchPFOvr_ctl00_EPay_TB_EPay',
    RateCom: '#ctl00_MainContent_GridBranchPFOvr_ctl00_MainContent_GridBranchPFOvr_ctl00_CPay_TB_CPay',
    SaveProviden: '#ctl00_MainContent_GridBranchPFOvr_ctl00_ctl02_ctl00_SaveChangesIcon',
    closesitting: '//*[@id="RadWindowWrapper_ctl00_RadWindow1"]/div[1]/div/ul/li/span',

    // Attendance Time Settings
    TotalWorkingDaysT: '#MainContent_txtMonthProcess',
    TotalWorkingHoursT: '#MainContent_txtHourProcess',
    // Overtime Settings
    TotalWorkingDaysOT: '#MainContent_txtMonthProcessOT',
    TotalWorkingHoursOT: '#MainContent_txtHourProcessOT',

    // Employee Welfare Fund
    Calforprovid: '#MainContent_ckCheckBoxEWF > label',
    Empcel: '#MainContent_txtEWFPay',
    Associatecom: '#MainContent_txtEWFCPay',
    Dateoffundentering: '#MainContent_txtEWFDateStart',
    Dateoffundleaving: '#MainContent_txtEWFDateExit',

    // Calculation method/deduction
    // Personnel allowance
    TabCalmethod: '//*[@id="ctl00_MainContent_RadTabStrip4"]/div/ul/li[2]/span/span',
    TabPersonnelallowance: '//*[@id="ctl00_MainContent_RadTabStrip3"]/div/ul/li[1]/span/span',
    Governmentnotexceeding: '#MainContent_txtCollect',
    AnnualPremium: '#MainContent_txtInsurePerson',
    PensionPremium: '#MainContent_txtEmpPensionIns',
    RMF: '#MainContent_txtRMF',
    FinancialSupport: '#MainContent_txtStudy', //support for education and sports
    PrivateAssistanceFund: '#MainContent_txtComfort',
    MajorCitiesTourism: '#MainContent_txtTour',
    Maternityexpenses: '#MainContent_txtANC',
    Healthinsurance: '#MainContent_txtHealth',
    Homerent: '#MainContent_txtSSFHome2',
    SolarEnergySystem: '#MainContent_txtSolarTax',
    Housingtax: '#MainContent_txt_ThaiESG',
    ThaiESGXNew: '#MainContent_txt_ThaiESGX',
    ThaiESGXOriginalLTFYear1: '#MainContent_txt_ThaiESGX2',
    ThaiESGXLTFexcess300000baht: '#MainContent_txt_ThaiESGX3',
    Spouseempstatus: '#ctl00_MainContent_Combo_WorkSpouse_Input',
    SpouseempstatusList: '#ctl00_MainContent_Combo_WorkSpouse_DropDown',
    Taxcommarriedcouples: '#ctl00_MainContent_Combo_SpouseTaxType_Input',
    Annualinterestonhousing: '#MainContent_txtInterest',
    SSF: '#MainContent_txtLTF',
    Supportdisabledincapac: '#MainContent_txtHandicap',
    Totalannualdonations: '#MainContent_txtDonate',
    Secondaryprovinces: '#MainContent_txtTour2',
    Childbirthexpenses: '#MainContent_txtConfined',
    Politicaldonations: '#MainContent_txt_Partydonate',
    PFSavingnation: '#MainContent_txtPFSavingnation',

    // Child born before 2018 or firstborn child // ยังไม่ทำ
    Childtaxdeductionof30000: '#MainContent_txtChildStudy',
    IDcardnumberofthefirstchildB: '#MainContent_txtIdenStu1',
    IDcardnumberesecondchildB: '#MainContent_txtIdenStu2',
    IDcardthirdchildB: '#MainContent_txtIdenStu3',

    //  Second child born in or after 2018
    Childtaxdeductionof60000: '#MainContent_txtChildNoStudy',
    IDcardnumberofthefirstchildA: '#MainContent_txtIdenNStu1',
    IDcardnumberesecondchildA: '#MainContent_txtIdenNStu2',
    IDcardthirdchildA: '#MainContent_txtIdenNStu3',

    // Identification number
    FatherIDCheck: '#MainContent_Panel3 > div:nth-child(1) > div > div > div > div:nth-child(2) > div > div:nth-child(1) > label',
    FatherIDtxt: '#MainContent_txtFatherID',
    MotherIDCheck: '#MainContent_Panel3 > div:nth-child(1) > div > div > div > div:nth-child(3) > div > div:nth-child(1) > label',
    MotherIDtxt: '#MainContent_txtMatherID',
    Fatherinsurancepremium: '#MainContent_Panel3 > div:nth-child(1) > div > div > div > div:nth-child(4) > div > div:nth-child(1) > label',
    Fatherinsurancepremiumtxt: '#MainContent_txtInsAmtF',
    Motherinsurancepremium: '#MainContent_Panel3 > div:nth-child(1) > div > div > div > div.form-group.mb-1 > div > div:nth-child(1) > label',
    Motherinsurancepremiumtxt: '#MainContent_txtInsAmtM',
    Maritalstatusnotthroughout: '#MainContent_Panel3 > div:nth-child(2) > div > div > div > div:nth-child(1) > div > div > label',
    Disabled: '#MainContent_Panel3 > div:nth-child(2) > div > div > div > div:nth-child(2) > div > div > label',
    OverAge: '#MainContent_Panel3 > div:nth-child(2) > div > div > div > div.form-group.mb-1 > div > div > label',

    // Spouse allowance Personal Deduction
    TabSpouseallowance: '//*[@id="ctl00_MainContent_RadTabStrip3"]/div/ul/li[2]/span/span',
    GovernmentnotexceedingS: '#MainContent_txtSPCollect', //Pension Fund not exceeding
    TotalannualdonationsS: '#MainContent_txtSPDonate',
    HousingtaxdeductioS: '#MainContent_txtSPInterest',
    FinancialSupportS: '#MainContent_txtSPStudy', //support for education and sports
    PrivateAssistanceFundS: '#MainContent_txtSPComfort',
    AnnualinsurancepremiumS: '#MainContent_txtInsure', //Annual Insurance premium
    RMFS: '#MainContent_txtSPRMF', //RMF

    // Spouse allowance Personal Deduction Identification number
    FatherIDCheckS: '#MainContent_PanelAllowanceSpouse > div > div > div:nth-child(2) > div > div:nth-child(2) > div > div:nth-child(1) > label',
    FatherIDtxtS: '#MainContent_txtSPFatherID',
    MotherIDCheckS: '#MainContent_PanelAllowanceSpouse > div > div > div:nth-child(2) > div > div:nth-child(3) > div > div:nth-child(1) > label',
    MotherIDtxtS: '#MainContent_txtSPMatherID',
    FatherinsurancepremiumS: '#MainContent_PanelAllowanceSpouse > div > div > div:nth-child(2) > div > div:nth-child(4) > div > div:nth-child(1) > label',
    FatherinsurancepremiumtxtS: '#MainContent_txtInsAmtFSW',
    MotherinsurancepremiumS: '#MainContent_PanelAllowanceSpouse > div > div > div:nth-child(2) > div > div:nth-child(5) > div > div:nth-child(1) > label',
    MotherinsurancepremiumtxtS: '#MainContent_txtInsAmtMSW',
    Spouseaged65incometax: '#MainContent_PanelAllowanceSpouse > div > div > div:nth-child(2) > div > div.form-group.mb-1 > div > div > label',

    // Spouse allowance  Spouse information
    FirstNameS: '#MainContent_MateFname',
    LastNameS: '#MainContent_MateLname',
    IdentificationnumberS: '#MainContent_MateIdentity',

    // Spouse allowance  SPSpouse
    TotalIncomeS: '#MainContent_txtSPTotalIncome',
    SSFS: '#MainContent_txtSPSSF',
    Taxfortheyear: '#MainContent_txtSPTax',
    Fundsfortheyear: '#MainContent_txtSPPF',

    // YearAllowance
    TabYearAllowance: '//*[@id="ctl00_MainContent_RadTabStrip3"]/div/ul/li[3]/span/span',
    ShopDeeMeeKuen: '#MainContent_txtFestival',
    FestivalY1: '#MainContent_txtFestival_1',
    FestivalY2: '#MainContent_txtFestival_2',



    // Total Salary
    TabSalary: '//*[@id="ctl00_MainContent_RadTabStrip4"]/div/ul/li[3]/span/span',
    RateofSalary: '#MainContent_DECRYPT_Salary',
    EmailSlip: '#MainContent_Txt_EmailSlip',
    PayType: '#ctl00_MainContent_Combo_PayTypeID_Input',
    PayTypeList: '#ctl00_MainContent_Combo_PayTypeID_DropDown',
    AccountNO: '#MainContent_AccountNO',
    BankName: '#ctl00_MainContent_Combo_BankNameID_Input',
    BankNameList: '#ctl00_MainContent_Combo_BankNameID_DropDown',
    BranchBank: '#ctl00_MainContent_Combo_BranchBankID_Input',
    BranchBankList: '#ctl00_MainContent_Combo_BranchBankID_DropDown',
    NationT: '#MainContent_PanelSararys > div > div > div > div > div:nth-child(6) > div > div > label',

    // Processing period
    Period1: '#MainContent_PanelSararys > div > div > div > div > div.form-group.my-3 > div > div:nth-child(1) > label',
    Period2: '#MainContent_PanelSararys > div > div > div > div > div.form-group.my-3 > div > div:nth-child(2) > label',
    Period3: '#MainContent_PanelSararys > div > div > div > div > div.form-group.my-3 > div > div:nth-child(3) > label',
    Period4: '#MainContent_PanelSararys > div > div > div > div > div.form-group.my-3 > div > div:nth-child(4) > label',
    Period5: '#MainContent_PanelSararys > div > div > div > div > div.form-group.my-3 > div > div:nth-child(5) > label',
    PeriodSpecial: '#MainContent_PanelSararys > div > div > div > div > div.form-group.my-3 > div > div:nth-child(6) > label',
    RateOT6: '#MainContent_txtOT6',

    // Documents
    TabDocuments: '//*[@id="ctl00_MainContent_RadTabStrip1"]/div/ul/li[9]/span/span',
    NationalID: '#ctl00_MainContent_Upload_NationalIDfile0',
    WorkCertificate: '#ctl00_MainContent_Upload_Workfile0',
    Bankaccount: '#ctl00_MainContent_Upload_Bankfile0',

    MarriageCertificate: '#ctl00_MainContent_Upload_Marriagefile0',
    OtherDocuments: '#ctl00_MainContent_Upload_MarriageOtherfile0',

    OtherDocuments1: '#ctl00_MainContent_Upload_Doc1file0',
    OtherDocuments2: '#ctl00_MainContent_Upload_Doc2file0',
    PDPAConsent: '#MainContent_lblPDPAView',
    closePDPA: '#modal_PDPA > div > div > div.modal-header > button',

    DeleteButton: '#MainContent_PanelDelNational > button',
    DeleteButton2: '#MainContent_PanelDelWork > button',
    DeleteButton3: '#MainContent_PanelDelBank > button',
    DeleteButton4: '#MainContent_PanelDelMarriage > button',
    DeleteButton5: '#MainContent_PanelDelDocMarriageOther > button',
    DeleteButton6: '#MainContent_PanelDelDoc1 > button',
    DeleteButton7: '#MainContent_PanelDelDoc2 > button',

};